### ISSUE TITLE
not working on windows

### ISSUE THREAD

**Issue by rafariva** [Kelian98/tau2_thermalcapture#1]
hi, i am trying to capture thermal images with a tau2 on my windows, using the usb cable conected to the serial port of the camera.
I am trying to use your code, but i cant install the 'smbus library'. any guess? thanks

**Comment by Kelian98** [comment]
Hi!
smbus library is made for the Raspberry Pi controller, whose goal is to read temperature from sensors.
For your usage, you can remove everything related to it.
I will enhance the current code in order to be as basic as possible for users.
